name: Build and deploy Docker to Azure Function App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push Docker image
        run: |
          docker build -t dwh-api .
          az webapp config container set \
            --name DWH-API \
            --resource-group RG-ANALITICA \
            --docker-custom-image-name dwh-api
